name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build client
      working-directory: ./client
      run: cargo build --verbose
    - name: Run client tests
      run: cargo test --verbose
    - name: Build server
      working-directory: ./server
      run: cargo build --verbose
    - name: Run server tests
      run: cargo test --verbose
